# 1. Use lightweight Java image
FROM eclipse-temurin:21-jre

# 2. Set working directory inside container
WORKDIR /app

# 3. Copy jar file into container
COPY target/*.jar app.jar

# 4. Expose app port
EXPOSE 8080

# 5. Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
